# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ef40613a713a94e0edca0468cceb05d24a71605d5df9624df24506915a935d0d3b88511d4773bb3bffc88f8fbba57c0e74a560eed812df865c3043f5ee17fe4

test:
  secret_key_base: 6179159049469f25cd4414746f6a81027b7f9d9c261b137b97cd6c5f09ea26461fb81335d30fb137462f89dfcdebc5a72d4cf08ead02901938e065eee06915e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
